"""init

Revision ID: 6a30e706db0d
Revises: 
Create Date: 2025-01-10 21:47:05.979670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a30e706db0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_data',
    sa.Column('site_url', sa.String(length=300), nullable=False),
    sa.Column('tender_info_link', sa.String(length=300), nullable=True),
    sa.Column('tender_number', sa.String(length=300), nullable=False),
    sa.Column('purchase_object', sa.Text(), nullable=True),
    sa.Column('customer', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('documents_info', sa.JSON(), nullable=True),
    sa.Column('amount_parsed_files', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('site_url', 'tender_number', name='pk_site_url_tender_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_data')
    # ### end Alembic commands ###
