# Generated by Django 4.2.14 on 2025-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avia_transportation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название'),
        ),
    ]
